[package]
name = "doki"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.3"
rustc-hash = "1.1.0"
stripmargin = "*"
strum = { version = "0.24", features = ["derive"] }
once_cell = "1.8.0"
unic-ucd-category = "0.9.0"
