[package]
name = "doki"
version = "0.1.0"
edition = "2021"

[workspace]
default-members = ["."]
members = [".", "doki-ir"]

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
chumsky = { git = "https://github.com/zesterer/chumsky" }
doki-ir = { path = "doki-ir" }
rustc-hash = "1.1.0"
tempfile = "3.5.0"
easy-ext = "1.0.1"
ariadne = "0.2.0"

[dev-dependencies]
assert_cmd = "2.0.4"
